#pragma once
// This file is generated by ./gfxBuilder

extern const unsigned char GD_SpaceBG_c[];
#define GD_SpaceBG_c_BANK 8
#define GD_SpaceBG_c_SIZE 7280

extern const unsigned char GD_BattleUI_c[];
#define GD_BattleUI_c_BANK 8
#define GD_BattleUI_c_SIZE 4096

extern const unsigned char GD_SpaceBG_p[];
#define GD_SpaceBG_p_BANK 8
#define GD_SpaceBG_p_SIZE 1024

extern const unsigned char GD_OShip0_c[];
#define GD_OShip0_c_BANK 8
#define GD_OShip0_c_SIZE 2048

extern const unsigned char GD_OShips_p[];
#define GD_OShips_p_BANK 8
#define GD_OShips_p_SIZE 184

extern const unsigned char GD_Title_p[];
#define GD_Title_p_BANK 8
#define GD_Title_p_SIZE 896

extern const unsigned char GD_SolarXY[];
#define GD_SolarXY_BANK 8
#define GD_SolarXY_SIZE 128

extern const unsigned char GD_Galaxy_t[];
#define GD_Galaxy_t_BANK 8
#define GD_Galaxy_t_SIZE 360

extern const unsigned char GD_Galaxy_a[];
#define GD_Galaxy_a_BANK 8
#define GD_Galaxy_a_SIZE 360

extern const unsigned char GD_OShip1_c[];
#define GD_OShip1_c_BANK 9
#define GD_OShip1_c_SIZE 2048

extern const unsigned char GD_OShip2_c[];
#define GD_OShip2_c_BANK 9
#define GD_OShip2_c_SIZE 2048

extern const unsigned char GD_OShip3_c[];
#define GD_OShip3_c_BANK 9
#define GD_OShip3_c_SIZE 2048

extern const unsigned char GD_OShip4_c[];
#define GD_OShip4_c_BANK 9
#define GD_OShip4_c_SIZE 2048

extern const unsigned char GD_OShip5_c[];
#define GD_OShip5_c_BANK 9
#define GD_OShip5_c_SIZE 2048

extern const unsigned char GD_OShip6_c[];
#define GD_OShip6_c_BANK 9
#define GD_OShip6_c_SIZE 2048

extern const unsigned char GD_OShip7_c[];
#define GD_OShip7_c_BANK 9
#define GD_OShip7_c_SIZE 2048

extern const unsigned char GD_Title_t[];
#define GD_Title_t_BANK 9
#define GD_Title_t_SIZE 1024

extern const unsigned char GD_Galaxy_i[];
#define GD_Galaxy_i_BANK 9
#define GD_Galaxy_i_SIZE 360

extern const unsigned char GD_Ships_bt[];
#define GD_Ships_bt_BANK 9
#define GD_Ships_bt_SIZE 46

extern const unsigned char GD_OShip8_c[];
#define GD_OShip8_c_BANK 10
#define GD_OShip8_c_SIZE 2048

extern const unsigned char GD_OShip9_c[];
#define GD_OShip9_c_BANK 10
#define GD_OShip9_c_SIZE 2048

extern const unsigned char GD_OShip10_c[];
#define GD_OShip10_c_BANK 10
#define GD_OShip10_c_SIZE 2048

extern const unsigned char GD_OShip11_c[];
#define GD_OShip11_c_BANK 10
#define GD_OShip11_c_SIZE 2048

extern const unsigned char GD_OShip12_c[];
#define GD_OShip12_c_BANK 10
#define GD_OShip12_c_SIZE 2048

extern const unsigned char GD_OShip13_c[];
#define GD_OShip13_c_BANK 10
#define GD_OShip13_c_SIZE 2048

extern const unsigned char GD_OShip14_c[];
#define GD_OShip14_c_BANK 10
#define GD_OShip14_c_SIZE 2048

extern const unsigned char GD_Title_a[];
#define GD_Title_a_BANK 10
#define GD_Title_a_SIZE 1024

extern const unsigned char GD_OShip15_c[];
#define GD_OShip15_c_BANK 11
#define GD_OShip15_c_SIZE 2048

extern const unsigned char GD_OShip16_c[];
#define GD_OShip16_c_BANK 11
#define GD_OShip16_c_SIZE 2048

extern const unsigned char GD_OShip17_c[];
#define GD_OShip17_c_BANK 11
#define GD_OShip17_c_SIZE 2048

extern const unsigned char GD_OShip18_c[];
#define GD_OShip18_c_BANK 11
#define GD_OShip18_c_SIZE 2048

extern const unsigned char GD_OShip19_c[];
#define GD_OShip19_c_BANK 11
#define GD_OShip19_c_SIZE 2048

extern const unsigned char GD_OShip20_c[];
#define GD_OShip20_c_BANK 11
#define GD_OShip20_c_SIZE 2048

extern const unsigned char GD_OShip21_c[];
#define GD_OShip21_c_BANK 11
#define GD_OShip21_c_SIZE 2048

extern const unsigned char GD_Ships_p[];
#define GD_Ships_p_BANK 11
#define GD_Ships_p_SIZE 1472

extern const unsigned char GD_OShip22_c[];
#define GD_OShip22_c_BANK 12
#define GD_OShip22_c_SIZE 2048

extern const unsigned char GD_Title_c[];
#define GD_Title_c_BANK 12
#define GD_Title_c_SIZE 5872

extern const unsigned char GD_SinCos[];
#define GD_SinCos_BANK 12
#define GD_SinCos_SIZE 8192

extern const unsigned char GD_StarrySky[];
#define GD_StarrySky_BANK 13
#define GD_StarrySky_SIZE 16384

extern const unsigned char GD_SolarSystem[];
#define GD_SolarSystem_BANK 14
#define GD_SolarSystem_SIZE 6272

extern const unsigned char GD_Ships_pship0_c[];
#define GD_Ships_pship0_c_BANK 14
#define GD_Ships_pship0_c_SIZE 4096

extern const unsigned char GD_Ships_pship1_c[];
#define GD_Ships_pship1_c_BANK 14
#define GD_Ships_pship1_c_SIZE 4096

extern const unsigned char GD_Ships_d[];
#define GD_Ships_d_BANK 14
#define GD_Ships_d_SIZE 1472

extern const unsigned char GD_PlanetNames[];
#define GD_PlanetNames_BANK 15
#define GD_PlanetNames_SIZE 16384

extern const unsigned char GD_Ships_pship2_c[];
#define GD_Ships_pship2_c_BANK 16
#define GD_Ships_pship2_c_SIZE 4096

extern const unsigned char GD_Ships_ship0_c[];
#define GD_Ships_ship0_c_BANK 16
#define GD_Ships_ship0_c_SIZE 4096

extern const unsigned char GD_Ships_ship1_c[];
#define GD_Ships_ship1_c_BANK 16
#define GD_Ships_ship1_c_SIZE 4096

extern const unsigned char GD_Ships_ship2_c[];
#define GD_Ships_ship2_c_BANK 17
#define GD_Ships_ship2_c_SIZE 4096

extern const unsigned char GD_Ships_ship3_c[];
#define GD_Ships_ship3_c_BANK 17
#define GD_Ships_ship3_c_SIZE 4096

extern const unsigned char GD_Ships_ship4_c[];
#define GD_Ships_ship4_c_BANK 17
#define GD_Ships_ship4_c_SIZE 4096

extern const unsigned char GD_Ships_ship5_c[];
#define GD_Ships_ship5_c_BANK 18
#define GD_Ships_ship5_c_SIZE 4096

extern const unsigned char GD_Ships_ship6_c[];
#define GD_Ships_ship6_c_BANK 18
#define GD_Ships_ship6_c_SIZE 4096

extern const unsigned char GD_Ships_ship7_c[];
#define GD_Ships_ship7_c_BANK 18
#define GD_Ships_ship7_c_SIZE 4096

extern const unsigned char GD_Ships_ship8_c[];
#define GD_Ships_ship8_c_BANK 19
#define GD_Ships_ship8_c_SIZE 4096

extern const unsigned char GD_Ships_ship9_c[];
#define GD_Ships_ship9_c_BANK 19
#define GD_Ships_ship9_c_SIZE 4096

extern const unsigned char GD_Ships_ship10_c[];
#define GD_Ships_ship10_c_BANK 19
#define GD_Ships_ship10_c_SIZE 4096

extern const unsigned char GD_Ships_ship11_c[];
#define GD_Ships_ship11_c_BANK 20
#define GD_Ships_ship11_c_SIZE 4096

extern const unsigned char GD_Ships_ship12_c[];
#define GD_Ships_ship12_c_BANK 20
#define GD_Ships_ship12_c_SIZE 4096

extern const unsigned char GD_Ships_ship13_c[];
#define GD_Ships_ship13_c_BANK 20
#define GD_Ships_ship13_c_SIZE 4096

extern const unsigned char GD_Ships_ship14_c[];
#define GD_Ships_ship14_c_BANK 21
#define GD_Ships_ship14_c_SIZE 4096

extern const unsigned char GD_Ships_ship15_c[];
#define GD_Ships_ship15_c_BANK 21
#define GD_Ships_ship15_c_SIZE 4096

extern const unsigned char GD_Ships_ship16_c[];
#define GD_Ships_ship16_c_BANK 21
#define GD_Ships_ship16_c_SIZE 4096

extern const unsigned char GD_Ships_ship17_c[];
#define GD_Ships_ship17_c_BANK 22
#define GD_Ships_ship17_c_SIZE 4096

extern const unsigned char GD_Ships_ship18_c[];
#define GD_Ships_ship18_c_BANK 22
#define GD_Ships_ship18_c_SIZE 4096

extern const unsigned char GD_Ships_ship19_c[];
#define GD_Ships_ship19_c_BANK 22
#define GD_Ships_ship19_c_SIZE 4096

extern const unsigned char GD_Ships_t[];
#define GD_Ships_t_BANK 23
#define GD_Ships_t_SIZE 9200

extern const unsigned char GD_Ships_a[];
#define GD_Ships_a_BANK 24
#define GD_Ships_a_SIZE 9200

