#pragma once

// This file is automatically generated by running ./convMusic
// on the .z80 files generated by export-enabled P5 Tracker
// https://rv6502.ca/wiki/index.php?title=Game_Boy_Tracker

extern const unsigned char * const Inst_name[];
extern const unsigned char * const Music_name[];
extern const unsigned char * const Inst_name3[];
extern const unsigned char * const Music_name3[];
extern const unsigned char * const Inst_named[];
extern const unsigned char * const Music_named[];
extern const unsigned char * const Inst_noname[];
extern const unsigned char * const Music_noname[];
extern const unsigned char * const Inst_noname10[];
extern const unsigned char * const Music_noname10[];
extern const unsigned char * const Inst_noname11[];
extern const unsigned char * const Music_noname11[];
extern const unsigned char * const Inst_noname12[];
extern const unsigned char * const Music_noname12[];
extern const unsigned char * const Inst_noname13[];
extern const unsigned char * const Music_noname13[];
extern const unsigned char * const Inst_noname14[];
extern const unsigned char * const Music_noname14[];
extern const unsigned char * const Inst_noname15[];
extern const unsigned char * const Music_noname15[];
extern const unsigned char * const Inst_noname16[];
extern const unsigned char * const Music_noname16[];
extern const unsigned char * const Inst_noname17[];
extern const unsigned char * const Music_noname17[];
extern const unsigned char * const Inst_noname18[];
extern const unsigned char * const Music_noname18[];
extern const unsigned char * const Inst_noname19[];
extern const unsigned char * const Music_noname19[];
extern const unsigned char * const Inst_noname3[];
extern const unsigned char * const Music_noname3[];
extern const unsigned char * const Inst_noname4[];
extern const unsigned char * const Music_noname4[];
extern const unsigned char * const Inst_noname5[];
extern const unsigned char * const Music_noname5[];
extern const unsigned char * const Inst_noname6[];
extern const unsigned char * const Music_noname6[];
extern const unsigned char * const Inst_noname7[];
extern const unsigned char * const Music_noname7[];
extern const unsigned char * const Inst_noname8[];
extern const unsigned char * const Music_noname8[];
extern const unsigned char * const Inst_noname9[];
extern const unsigned char * const Music_noname9[];
extern const unsigned char * const SFX_Table[];
