// This file was generated by building SoundSystem.gb and running
// ./extractSoundSystem on it to save the library into a C array


#pragma once
#include <stdint.h>
extern const unsigned char GBSoundSystem[];

#define GBS_SoundSystem_Init 0x37e0
#define GBS_SoundSystem_Process 0x3510
#define GBS_Music_PrepareInst 0x3f6c
#define GBS_Music_Play 0x3934
#define GBS_Music_Pause 0x38e5
#define GBS_Music_Resume 0x3ff6
#define GBS_SFX_Prepare 0x3f76
#define GBS_SFX_Play 0x3da3
#define GBS_SFX_Stop 0x3845
#define GBS_SFX_LockChannel3 0x3d4a
#define GBS_SFX_UnlockChannel3 0x3e90
#define GBS_startOfVars 0xc000
#define GBS_endOfVars 0xc057
struct {
  uint8_t wMusicSyncData;
  uint8_t wSoundFXLock;
  uint16_t wSoundFXTable;
  uint8_t wSoundFXBank;
  uint8_t wSoundFXStart[4];
  uint8_t wSoundFXNote;
  uint8_t wMusicSFXPanning;
  uint8_t wMusicSFXInstPause1;
  uint8_t wMusicSFXInstPause2;
  uint8_t wMusicSFXInstPause3;
  uint8_t wMusicSFXInstPause4;
  uint16_t wMusicSFXInstPtr1;
  uint16_t wMusicSFXInstPtr2;
  uint16_t wMusicSFXInstPtr3;
  uint16_t wMusicSFXInstPtr4;
  uint8_t wMusicSFXInstBank1;
  uint8_t wMusicSFXInstBank2;
  uint8_t wMusicSFXInstBank3;
  uint8_t wMusicSFXInstBank4;
  uint8_t wMusicSFXInstChnl3WaveID;
  uint8_t wMusicSFXInstChnl3Lock;
  uint8_t wMusicPlayState;
  uint8_t wMusicNextFrame;
  uint16_t wMusicCommandPtr;
  uint8_t wMusicCommandBank;
  uint16_t wMusicOrderPtr;
  uint8_t wMusicOrderBank;
  uint16_t wMusicInstrumentTable;
  uint8_t wMusicInstrumentBank;
  uint16_t wChannelMusicFreq1;
  uint16_t wChannelMusicFreq2;
  uint16_t wChannelMusicFreq3;
  uint16_t wChannelMusicFreq4;
  uint8_t wChannelMusicNote1;
  uint8_t wChannelMusicNote2;
  uint8_t wChannelMusicNote3;
  uint8_t wChannelMusicNote4;
  uint16_t wChannelFreq1;
  uint16_t wChannelFreq2;
  uint16_t wChannelFreq3;
  uint16_t wChannelFreq4;
  uint8_t wChannelVol1;
  uint8_t wChannelVol2;
  uint8_t wChannelVol3;
  uint8_t wChannelVol4;
  uint8_t wMusicSpeed;
  uint8_t wChannelMusicEffect1;
  uint8_t wChannelMusicEffect2;
  uint8_t wChannelMusicEffect3;
  uint8_t wChannelMusicEffect4;
  uint16_t wChannelMusicFXParamA1;
  uint16_t wChannelMusicFXParamA2;
  uint16_t wChannelMusicFXParamA3;
  uint16_t wChannelMusicFXParamA4;
  uint16_t wChannelMusicFXParamB1;
  uint16_t wChannelMusicFXParamB2;
  uint16_t wChannelMusicFXParamB3;
  uint16_t wChannelMusicFXParamB4;
  uint16_t wTemp;
} __at(0xc000) GBS_Vars;
